version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  redis-langcache:
    build: ./redis-langcache-service
    container_name: redis-langcache
    ports:
      - "8081:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - redis

  ollama-bge:
    build:
      context: ./custom-embeddings
      dockerfile: Dockerfile
    container_name: ollama-bge
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=${REDIS_URL}
      - EMBEDDING_MODEL=BAAI/bge-m3

  openai-embeddings:
    build:
      context: ./openai-embeddings
      dockerfile: Dockerfile
    container_name: openai-embeddings
    ports:
      - "8082:8080"
    environment:
      - REDIS_URL=${REDIS_URL}
      - EMBEDDING_MODEL=text-embedding-small
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  redis_data:
