services:
  - type: web
    name: langcache-ollama
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
